package com.hfad.parkingfinder.geodata.osm.model;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum ProviderOsmType {
    @JsonProperty("alcohol")
    ALCOHOL,
    @JsonProperty("bakery")
    BAKERY,
    @JsonProperty("beverages")
    BEVERAGES,
    @JsonProperty("butcher")
    BUTCHER,
    @JsonProperty("cheese")
    CHEESE,
    @JsonProperty("chocolate")
    CHOCOLATE,
    @JsonProperty("confectionery")
    CONFECTIONERY,
    @JsonProperty("convenience")
    CONVENIENCE,
    @JsonProperty("deli")
    DELI,
    @JsonProperty("farm")
    FARM,
    @JsonProperty("greengrocer")
    GREENGROCER,
    @JsonProperty("frozen_food")
    FROZEN_FOOD,
    @JsonProperty("organic")
    ORGANIC,
    @JsonProperty("pasta")
    PASTA,
    @JsonProperty("seafood")
    SEAFOOD,
    @JsonProperty("tea")
    TEA,

    @JsonProperty("department_store")
    DEPARTMENT_STORE,
    @JsonProperty("general")
    GENERAL,
    @JsonProperty("mall")
    MALL,
    @JsonProperty("supermarket")
    SUPERMARKET,

    @JsonProperty("baby_goods")
    BABY_GOODS,
    @JsonProperty("bag")
    BAG,
    @JsonProperty("boutique")
    BOUTIQUE,
    @JsonProperty("clothes")
    CLOTHES,
    @JsonProperty("fabric")
    FABRIC,
    @JsonProperty("jewelry")
    JEWELRY,
    @JsonProperty("shoes")
    SHOES,

    @JsonProperty("charity")
    CHARITY,
    @JsonProperty("second_hand")
    SECOND_HAND,
    @JsonProperty("variety_store")
    VARIETY_STORE,

    @JsonProperty("beauty")
    BEAUTY,
    @JsonProperty("chemist")
    CHEMIST,
    @JsonProperty("drugstore")
    DRUGSTORE,
    @JsonProperty("erotic")
    EROTIC,
    @JsonProperty("hairdresser")
    HAIRDRESSER,
    @JsonProperty("hairdresser_supply")
    HAIRDRESSER_SUPPLY,
    @JsonProperty("hearing_aids")
    HEARING_AIDS,
    @JsonProperty("herbalist")
    HERBALIST,
    @JsonProperty("massage")
    MASSAGE,
    @JsonProperty("optician")
    OPTICIAN,
    @JsonProperty("tattoo")
    TATTOO,

    @JsonProperty("bathroom_furnishing")
    BATHROOM_FURNISHING,
    @JsonProperty("doityourself")
    DOITYOURSELF,
    @JsonProperty("fireplace")
    FIREPLACE,
    @JsonProperty("florist")
    FLORIST,
    @JsonProperty("garden_centre")
    GARDEN_CENTER,
    @JsonProperty("gas")
    GAS,
    @JsonProperty("glaziery")
    GLAZIERY,
    @JsonProperty("hardware")
    HARDWARE,
    @JsonProperty("houseware")
    HOUSEWARE,
    @JsonProperty("locksmith")
    LOCKSMITH,
    @JsonProperty("paint")
    PAINT,
    @JsonProperty("trade")
    TRADE,

    @JsonProperty("antiques")
    ANTIQUES,
    @JsonProperty("bed")
    BED,
    @JsonProperty("candles")
    CANDLES,
    @JsonProperty("carpet")
    CARPET,
    @JsonProperty("curtain")
    CURTAIN,
    @JsonProperty("furniture")
    FURNITURE,
    @JsonProperty("interior_decoration")
    INTERIOR_DECORATION,
    @JsonProperty("kitchen")
    KITCHEN,
    @JsonProperty("lamps")
    LAMPS,
    @JsonProperty("tiles")
    TITLES,
    @JsonProperty("window_blind")
    WINDOW_BLIND,

    @JsonProperty("computer")
    COMPUTER,
    @JsonProperty("electronics")
    ELECTRONICS,
    @JsonProperty("hifi")
    HIFI,
    @JsonProperty("mobile_phone")
    MOBILE_PHONE,
    @JsonProperty("radiotechnics")
    RADIOTECHNICS,
    @JsonProperty("vacuum_cleaner")
    VACUUM_CLEANER,

    @JsonProperty("bicycle")
    BICYCLE,
    @JsonProperty("car")
    CAR,
    @JsonProperty("car_repair")
    CAR_REPAIR,
    @JsonProperty("car_parts")
    CAR_PARTS,
    @JsonProperty("dive")
    DIVE,
    @JsonProperty("fishing")
    FISHING,
    @JsonProperty("free_flying")
    FREE_FLYING,
    @JsonProperty("hunting")
    HUNTING,
    @JsonProperty("motorcycle")
    MOTORCYCLE,
    @JsonProperty("outdoor")
    OUTDOOR,
    @JsonProperty("sports")
    SPORTS,

    @JsonProperty("art")
    ART,
    @JsonProperty("craft")
    CRAFT,
    @JsonProperty("frame")
    FRAME,
    @JsonProperty("music")
    MUSIC,
    @JsonProperty("musical_instrument")
    MUSICAL_INSTRUMENT,
    @JsonProperty("video")
    VIDEO,
    @JsonProperty("video_games")
    VIDEO_GAMES,

    @JsonProperty("anime")
    ANIME,
    @JsonProperty("books")
    BOOKS,
    @JsonProperty("gift")
    GIFT,
    @JsonProperty("newsagent")
    NEWSAGENT,
    @JsonProperty("stationery")
    STATIONERY,
    @JsonProperty("kiosk")
    KIOSK,
    @JsonProperty("ticket")
    TICKET,

    @JsonProperty("copyshop")
    COPYSHOP,
    @JsonProperty("dry_cleaning")
    DRY_CLEANING,
    @JsonProperty("funeral_directors")
    FUNREAL_DIRECTORS,
    @JsonProperty("laundry")
    LAUNDRY,
    @JsonProperty("money_lender")
    MONEY_LENDER,
    @JsonProperty("pawnbroker")
    PAWNBROKER,
    @JsonProperty("pet")
    PET,
    @JsonProperty("pyrotechnics")
    PYROTECHNICS,
    @JsonProperty("religion")
    RELIGION,
    @JsonProperty("storage_rental")
    STORAGE_RENTAL,
    @JsonProperty("tobacco")
    TOBACCO,
    @JsonProperty("toys")
    TOYS,
    @JsonProperty("vacant")
    VACANT,
    @JsonProperty("weapons")
    WEAPONS,
}
